apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
data:
  password: cm9vdA==
  database: YW5pbWVfbGlzdA==
  # Example:
  # password: {{ .Values.password | b64enc }}